/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlatformerRouteImport } from './routes/platformer'
import { Route as IndexRouteImport } from './routes/index'

const PlatformerRoute = PlatformerRouteImport.update({
  id: '/platformer',
  path: '/platformer',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/platformer': typeof PlatformerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/platformer': typeof PlatformerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/platformer': typeof PlatformerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/platformer'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/platformer'
  id: '__root__' | '/' | '/platformer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlatformerRoute: typeof PlatformerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/platformer': {
      id: '/platformer'
      path: '/platformer'
      fullPath: '/platformer'
      preLoaderRoute: typeof PlatformerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlatformerRoute: PlatformerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
